# nixpacks.toml

providers = ["python", "node"]

[phases.install]
cmds = [
    "npm install --prefix frontend", # Install frontend dependencies
    "pip install -r backend/requirements.txt" # Install backend dependencies
]

[start]
cmd = "./start.sh" # Run your start script