# nixpacks.toml

providers = ["python", "node"]

[phases.install]
cmds = [
    "npm --prefix frontend install",
    "python3 -m pip install -r backend/requirements.txt" # Change this line
]

[start]
cmd = "./start.sh" # Run your start script